import tokensJson from "./tokens.json";

/**
 * Resolved token values for JS consumers that cannot use CSS variables, such as canvas overlays.
 * Colours are `#rrggbb` or `rgba(r, g, b, a)`; space and radius are px numbers. Generated by
 * `pnpm tokens`; components keep using the Tailwind classes from theme.css.
 */
export const tokens = tokensJson;

export type Tokens = typeof tokensJson;
export type ThemeMode = keyof Tokens["color"];
export type ColourToken = keyof Tokens["color"]["light"];

/** The resolved colour of a semantic token in one theme, for example `colour("status-flag", "dark")`. */
export function colour(name: ColourToken, mode: ThemeMode = "light"): string {
  return tokens.color[mode][name];
}
