// Copies packages/contracts/src into supabase/functions/_shared/contracts/ so Edge Functions (Deno) run
// the same contracts as the apps. Run from the repo root: `pnpm functions:sync` (tsx).
//   --check   exit 1 when the copy is missing or out of date, without writing
//
// Every runtime file (*.ts except *.test.ts) is copied with a header. Stale files in the target are
// deleted first. A file that imports anything except "zod" or a relative "./x.ts" stops the sync,
// because Deno could not resolve it.
//
// Two more generated files go next to them for the emails the functions send (send-invites, 0.8):
// `email-messages.ts`, the catalog's `email.*` messages in en, kk and ru, and `email-tokens.ts`, the
// light colours, radii and spacing from packages/tokens.
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = join(ROOT, "packages/contracts/src");
const TARGET = join(ROOT, "supabase/functions/_shared/contracts");
const HEADER = "// generated by pnpm functions:sync from packages/contracts/src, do not edit\n";
const CATALOG = join(ROOT, "packages/i18n/catalog.json");
const TOKENS = join(ROOT, "packages/tokens/src/tokens.json");
const EMAIL_LOCALES = ["en", "kk", "ru"] as const;

interface CatalogEntry {
  key: string;
  en?: string;
  kk?: string;
  ru?: string;
}

/** The catalog's `email.*` messages per language, as a TypeScript module. */
function emailMessagesModule(catalog: { keys: readonly CatalogEntry[] }): string {
  const messages: Record<string, Record<string, string>> = { en: {}, kk: {}, ru: {} };
  for (const entry of catalog.keys) {
    if (!entry.key.startsWith("email.")) continue;
    for (const locale of EMAIL_LOCALES) {
      const text = entry[locale];
      if (text === undefined || text === "") throw new Error(`${entry.key}: no ${locale} message`);
      const forLocale = messages[locale];
      if (forLocale) forLocale[entry.key] = text;
    }
  }
  return (
    "// generated by pnpm functions:sync from packages/i18n/catalog.json, do not edit\n" +
    `export const EMAIL_MESSAGES = ${JSON.stringify(messages, null, 2)} as const;\n`
  );
}

/** The light theme's colours, the radii and the spacing scale, as a TypeScript module. */
function emailTokensModule(tokens: {
  color: { light: Record<string, string> };
  radius: Record<string, number>;
  space: Record<string, number>;
}): string {
  const picked = { color: tokens.color.light, radius: tokens.radius, space: tokens.space };
  return (
    "// generated by pnpm functions:sync from packages/tokens/src/tokens.json, do not edit\n" +
    `export const EMAIL_TOKENS = ${JSON.stringify(picked, null, 2)} as const;\n`
  );
}

const IMPORT_SPECIFIER =
  /(?:^|\n)\s*(?:import|export)\s[^;]*?from\s*["']([^"']+)["']|import\(\s*["']([^"']+)["']\s*\)/g;

function isRuntimeFile(name: string): boolean {
  return name.endsWith(".ts") && !name.endsWith(".test.ts") && !name.endsWith(".d.ts");
}

function checkImports(name: string, source: string, files: ReadonlySet<string>): string[] {
  const problems: string[] = [];
  for (const match of source.matchAll(IMPORT_SPECIFIER)) {
    const specifier = match[1] ?? match[2];
    if (specifier === undefined || specifier === "zod") continue;
    const local = /^\.\/([a-z0-9-]+\.ts)$/.exec(specifier);
    if (!local) {
      problems.push(`${name}: import "${specifier}" is neither "zod" nor "./<file>.ts"`);
    } else if (!files.has(local[1] ?? "")) {
      problems.push(`${name}: import "${specifier}" is not a runtime file in packages/contracts/src`);
    }
  }
  return problems;
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  const names = (await readdir(SOURCE)).filter(isRuntimeFile).sort();
  const files = new Set(names);

  const outputs = new Map<string, string>();
  const problems: string[] = [];
  for (const name of names) {
    const source = await readFile(join(SOURCE, name), "utf8");
    problems.push(...checkImports(name, source, files));
    outputs.set(name, HEADER + source);
  }
  outputs.set("email-messages.ts", emailMessagesModule(JSON.parse(await readFile(CATALOG, "utf8"))));
  outputs.set("email-tokens.ts", emailTokensModule(JSON.parse(await readFile(TOKENS, "utf8"))));
  if (problems.length > 0) {
    console.error(`functions:sync: refused\n  ${problems.join("\n  ")}`);
    process.exit(1);
  }

  const target = relative(ROOT, TARGET);
  if (check) {
    const existing = await readdir(TARGET).catch(() => [] as string[]);
    const stale = existing.filter((name) => !outputs.has(name));
    const changed: string[] = [];
    for (const [name, content] of outputs) {
      const current = await readFile(join(TARGET, name), "utf8").catch(() => null);
      if (current !== content) changed.push(name);
    }
    if (stale.length > 0 || changed.length > 0) {
      console.error(
        `functions:sync --check: ${target} is out of date (changed: ${changed.join(", ") || "none"}; stale: ${stale.join(", ") || "none"}). Run pnpm functions:sync.`,
      );
      process.exit(1);
    }
    console.log(`functions:sync --check: ${target} matches ${outputs.size} files`);
    return;
  }

  await rm(TARGET, { recursive: true, force: true });
  await mkdir(TARGET, { recursive: true });
  for (const [name, content] of outputs) {
    await writeFile(join(TARGET, name), content, "utf8");
  }
  console.log(`functions:sync: wrote ${outputs.size} files to ${target}: ${[...outputs.keys()].join(", ")}`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
