import en from "../messages/en.json";
import kk from "../messages/kk.json";
import ru from "../messages/ru.json";
import type { Locale } from "./locales.ts";

/**
 * Message shape, from the English file: every catalog key plus the dashboard.* keys.
 * The files are generated by `pnpm i18n:build` from catalog.json and the dashboard*.json files.
 */
export type Messages = typeof en;

const byLocale = { en, kk, ru } as const;

/**
 * The nested messages for one locale. Kazakh and Russian carry every catalog key; Russian also
 * carries every dashboard key (the build fails otherwise), and Kazakh, which has no dashboard
 * namespace, falls back to the English one.
 */
export function loadMessages(locale: Locale): Messages {
  if (locale === "en") return en;
  return { ...en, ...byLocale[locale] };
}

/**
 * The labels of the language switch, ҚАЗ, РУС and ENG, from the catalog's language.* keys. They read
 * the same in every language, so they come from the English file.
 */
export const LOCALE_LABELS: Readonly<Record<Locale, string>> = {
  kk: en.language.kk,
  ru: en.language.ru,
  en: en.language.en,
};
