import en from "../messages/en.json";
import kk from "../messages/kk.json";
import ru from "../messages/ru.json";
import type { Locale } from "./locales.ts";

/**
 * Message shape, from the English file: every catalog key plus the English-only dashboard.* keys.
 * The files are generated by `pnpm i18n:build` from catalog.json and dashboard.json.
 */
export type Messages = typeof en;

const byLocale = { en, kk, ru } as const;

/**
 * The nested messages for one locale. Kazakh and Russian carry every catalog key; the dashboard
 * namespace is English only in Phase 0, so it falls back to English there.
 */
export function loadMessages(locale: Locale): Messages {
  if (locale === "en") return en;
  return { ...en, ...byLocale[locale] };
}

/**
 * The labels of the language switch, ҚАЗ, РУС and ENG, from the catalog's language.* keys. They read
 * the same in every language, so they come from the English file.
 */
export const LOCALE_LABELS: Readonly<Record<Locale, string>> = {
  kk: en.language.kk,
  ru: en.language.ru,
  en: en.language.en,
};
