// The Autumn 2026 term as SQL for supabase/seed.sql, so a fresh `supabase db reset` has the term without
// a script: the exams, who missed each one, and every flag, from buildTermPlan(). seed.sql builds the
// rosters and sessions from these rows with the same formulas as termSession() (term.ts), so the
// database and the plan agree row for row. `pnpm seed:term` writes this block into seed.sql between the
// two marker lines; `pnpm seed:term --check` and the unit tests fail when it is out of date.
//
// Review decisions need their reviewers' staff rows, which exist only after `pnpm seed:staff`, so that
// script writes them (writeTermDecisions in decisions.ts), and `pnpm demo:reset` writes everything.
import type { TermPlan } from "./term.ts";

export const BEGIN_MARK =
  "-- BEGIN seed v2 term data (generated by pnpm seed:term from scripts/lib/seed-v2, do not edit)";
export const END_MARK = "-- END seed v2 term data";

const quote = (value: string) => `'${value.replaceAll("'", "''")}'`;

/** Rows of a VALUES list, `perLine` to a line. */
function values(rows: readonly string[], perLine: number): string {
  const lines: string[] = [];
  for (let i = 0; i < rows.length; i += perLine) lines.push(`  ${rows.slice(i, i + perLine).join(", ")}`);
  return lines.join(",\n");
}

/** Seconds from the exam's start to `iso`; the plan keeps every time on a whole second. */
function offsetS(startsAt: string, iso: string): number {
  const ms = Date.parse(iso) - Date.parse(startsAt);
  if (ms % 1000 !== 0) throw new Error(`seed v2: ${iso} is not on a whole second`);
  return ms / 1000;
}

/** The generated DO block: inserts into the seed_v2 scratch tables that seed.sql creates before it. */
export function termDataSql(plan: TermPlan): string {
  const byIndex = new Map(plan.exams.map((exam) => [exam.index, exam]));
  const sessionNumber = new Map(plan.sessions.map((session) => [session.id, session.number]));
  const exams = plan.exams.map(
    (exam) =>
      `(${exam.index}, ${quote(exam.faculty)}, ${quote(exam.course)}, ${quote(exam.kind)}, ` +
      `array[${exam.groups.map(quote).join(", ")}], ${quote(exam.startsAt)}, ${exam.durationMin})`,
  );
  const absent = plan.absent.flatMap(({ examIndex, numbers }) =>
    numbers.map((number) => `(${examIndex}, ${quote(number)})`),
  );
  const flags = plan.events.map((event) => {
    const exam = plan.exams.find((row) => row.id === event.examId);
    if (!exam || byIndex.get(exam.index) !== exam) throw new Error(`seed v2: no exam for ${event.id}`);
    const k = Number(event.id.slice(-12));
    const number = sessionNumber.get(event.sessionId);
    if (number === undefined) throw new Error(`seed v2: no session for ${event.id}`);
    return (
      `(${exam.index}, ${k}, ${quote(number)}, ${quote(event.type)}, ${event.seq}, ` +
      `${offsetS(exam.startsAt, event.at)}, ${offsetS(exam.startsAt, event.receivedAt)}, ${quote(JSON.stringify(event.data))})`
    );
  });
  return [
    BEGIN_MARK,
    `-- ${plan.exams.length} exams, ${absent.length} absences, ${flags.length} flags (times in seconds from the exam's start).`,
    "do $seed_v2_term_data$",
    "begin",
    "",
    "insert into seed_v2.term_exams (idx, faculty, course, kind, groups, starts_at, duration_min) values",
    `${values(exams, 1)};`,
    "",
    "insert into seed_v2.term_absent (idx, student_number) values",
    `${values(absent, 6)};`,
    "",
    "insert into seed_v2.term_flags (idx, k, student_number, type, seq, at_s, received_s, data) values",
    `${values(flags, 1)};`,
    "",
    "end",
    "$seed_v2_term_data$;",
    END_MARK,
  ].join("\n");
}

/** `seed` with the text between the markers (markers included) replaced by `block`. */
export function spliceTermData(seed: string, block: string): string {
  const start = seed.indexOf(BEGIN_MARK);
  const end = seed.indexOf(END_MARK);
  if (start < 0 || end < start) throw new Error("seed v2: supabase/seed.sql has no term data markers");
  return `${seed.slice(0, start)}${block}${seed.slice(end + END_MARK.length)}`;
}
